<a href="https://colab.research.google.com/github/MdRufsan/Python-/blob/main/pandas/numpy/2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Learn NumPy**
NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".
fast
need less memory
ndarry object

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

**Arry attributes**

In [ ]:
#1D arry generates
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np

#1D arry generates
a=np.array([1,2,3])
a.shape #arry shape

(3,)

In [ ]:
# dimention name 1D arry=vector
a.ndim

1

In [ ]:
# 2D array
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.shape

(2, 3)

In [ ]:
b.ndim

2

**More array creation method**

In [ ]:
array1=np.array([1,2,3],dtype='int')
array1

array([1, 2, 3])

In [ ]:
z=np.zeros((2,3), order="C", dtype='int')  # ach element will be 0   ((shape),ordre,datatype)
z

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones((3,3), dtype='int')  # ach element will be 1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.full((3,3),5)  #modify values

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# identity matrix
identity_matrix1=np.eye(4, dtype='int')
identity_matrix1

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
identity_matrix2=np.identity(4, dtype='int')
identity_matrix2

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
identity_matrix3=np.eye(4,4,1) # (rows,cols,iteration k=1)
identity_matrix3

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
# arrange ()
arrange=np.arange(1,10,2) #(start,stop,step)
arrange

array([1, 3, 5, 7, 9])

In [ ]:
linspace=np.linspace(1,10,50,dtype='int') #(start,stop,number of elements)
linspace


array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

In [ ]:
linspace.size

50

In [ ]:
empty=np.empty((2,3))  # entry any value
empty

array([[1.20150959e-315, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

**Indexing and sliceing**

In [ ]:
# generate random integer
import numpy as np
a=np.random.randint(1,100,size=(3,5)) # 1-99 3*5 arry
print(a)

[[12 75  1 92 76]
 [99 61 28 58 80]
 [54 69 99 36 64]]


In [ ]:
import numpy as np
a=np.random.randint(1,100,5) # 1-99 integer contains 5 elements in a arry
print(a)

[87 35 25 33 64]


In [ ]:
import numpy as np
a=np.random.rand(2,3) # random float
print(a)

[[0.58339439 0.64367742 0.03732459]
 [0.79276794 0.54739074 0.24426144]]


In [ ]:
# sorting arry

a=np.array([3,1,7,2,0])
print('The arry is : ',a)
sorted_arr=np.sort(a)
print('The sorted arry is : ',sorted_arr)

The arry is :  [3 1 7 2 0]
The sorted arry is :  [0 1 2 3 7]


In [ ]:
# row wise sort in 2D array
import numpy as np
a=np.array([[3,1,7],
            [2,0,5]])

sorted_rows=np.sort(a, axis=1)
print('The sorted arry is : ',sorted_rows)

The sorted arry is :  [[1 3 7]
 [0 2 5]]


In [ ]:
# summation & multiplication a whole array with a number

a=np.array([[3,2,2],[4,5,6]])

display("Summation 10 : ",a+10)
display("Multiplication 10 : ",a*10)

'Summation 10 : '

array([[13, 12, 12],
       [14, 15, 16]])

'Multiplication 10 : '

array([[30, 20, 20],
       [40, 50, 60]])

In [ ]:
row=np.array([1,2,3])
result=a + row
display(result)

array([[ 4,  3, 10],
       [ 3,  2,  8]])

In [ ]:
#array reshape

arr=np.array([1,2,3,4,5,6])
print('Orginal array :',arr)
reshaped_arr=arr.reshape(2,3) # reshape in 2*3 matrix
print('Reshaped array :',reshaped_arr)

flattened=reshaped_arr.flatten() # return flat again
print('Flattened array :',flattened)

Orginal array : [1 2 3 4 5 6]
Reshaped array : [[1 2 3]
 [4 5 6]]
Flattened array : [1 2 3 4 5 6]


In [ ]:
# transpose

a=np.array([[1,2],[5,6]])
print('Orginal array :',a)
transposed=a.T
print('Transposed array :',transposed)

Orginal array : [[1 2]
 [5 6]]
Transposed array : [[1 5]
 [2 6]]


**Indexing and sliceing**

In [ ]:
# 1D array indexing

import numpy as np
a=np.array([1,2,3,4,5])
print(a[0])
print(a[-1])

1
5


In [ ]:
# 1D array slicing

import numpy as np
a=np.array([1,2,3,4,5])
print(a[0:3])
print(a[2:])

[1 2 3]
[3 4 5]


In [ ]:
# 2D array indexing
a=np.array([[1,2,3],[4,5,6]])
print(a[0,1]) # 1st row 2nd col
print(a[1,2]) # 2nd row 3rd col

2
6


In [ ]:
# 2D array slicing

a=np.array([[1,2,3],[4,5,6]])
print(a[:,1]) # all rows 2nd col
print(a[0,:]) # 1st row's all cols

[2 5]
[1 2 3]


In [ ]:
# boolean indexing (important for filtering)

import numpy as np
a=np.array([1,2,3,4,5,6])
print(a[a>2])

print(a[a%2==0])
print(a[a%2==1])

[3 4 5 6]
[2 4 6]
[1 3 5]


**Array operations**

In [ ]:
# arithmetic operations

import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# scalar operations

import numpy as np
a=np.array([1,2,3])
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]


In [ ]:
#matrix multiplication (dot product)

import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a.dot(b))
print(np.dot(a,b))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
# eliment wise square,power,root

import numpy as np
a=np.array([1,2,3])
print(np.square(a))
print(np.power(a,2))
print(np.sqrt(a))

[1 4 9]
[1 4 9]
[1.         1.41421356 1.73205081]


In [ ]:
# aggregate functions

import numpy as np
a=np.array([1,2,3,4,5])
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.var(a))
print(np.median(a))
print(np.percentile(a,25))
print(np.percentile(a,50))
print(np.percentile(a,75))
print(np.percentile(a,100))
print(np.percentile(a,0))
print(np.percentile(a,5))

15
3.0
1
5
1.4142135623730951
2.0
3.0
2.0
3.0
4.0
5.0
1.0
1.2


Missing values ,boolean masking & filtering

In [ ]:
# MSSING values(np.nan --> not a number)

import numpy as np

arr=np.array([1,2,3,np.nan,5])
print(arr)
print(np.isnan(arr)) # NaN check --> isnan()


[ 1.  2.  3. nan  5.]
[False False False  True False]


In [ ]:
# clean NaN

import numpy as np

arr=np.array([1,2,3,np.nan,5])
print(arr)

cleaned = arr[~np.isnan(arr)] # without NaN

print(cleaned)

[ 1.  2.  3. nan  5.]
[1. 2. 3. 5.]


In [ ]:
# find mean if remains NaN

import numpy as np

arr=np.array([1,2,3,np.nan,5])
print(arr)

mean=np.nanmean(arr) # mean without NaN values Mean=(1+2+3+5)/4=2.75
print(mean)

[ 1.  2.  3. nan  5.]
2.75


In [ ]:
# boolean masking & filtering

arr=np.array([10,20,30,5,50])
mask= arr >= 20
print(mask)

filtered_arr=arr[mask]
print(filtered_arr)


[False  True  True False  True]
[20 30 50]


In [ ]:
arr=np.array([10,20,30,5,50])
print('Between 20 & 40 : ', arr[(arr > 20) & (arr < 40)])
print('Not between 20 & 40 : ', arr[~(arr > 20) & (arr < 40)])

Between 20 & 40 :  [30]
Not between 20 & 40 :  [10 20  5]


In [ ]:
# 2d arrary filtering

a=np.array([[1,2,3],[4,5,6]])
print(a)
mask2d= a > 2
print(mask2d)
filtered_arr=a[mask2d]
print(filtered_arr)

[[1 2 3]
 [4 5 6]]
[[False False  True]
 [ True  True  True]]
[3 4 5 6]


**Aggregation fun()**

In [ ]:
import numpy as np

a=np.array([1,4,2,7,1])

In [ ]:
print('sum = ',np.sum(a))
print('mean = ',np.mean(a))
print('median = ',np.median(a))
print('std = ',np.std(a))
print('max= ',np.max(a))
print('min= ',np.min(a))
print('25th percentiles = ',np.percentile(a,25))

sum =  15
mean =  3.0
median =  2.0
std =  2.280350850198276
max=  7
min=  1
25th percentiles =  1.0


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print('Total Sum = ',np.sum(a))
print('Col wise sum = ',np.sum(a,axis=0))
print('Row wise sum = ',np.sum(a,axis=1))

Total Sum =  21
Col wise sum =  [5 7 9]
Row wise sum =  [ 6 15]


**Stacking**(eksathe jora lagano)

In [ ]:
# vstack --> vertically(up-down)
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

vstacked=np.vstack((a,b))
print(vstacked)

[[1 2 3]
 [4 5 6]]


In [ ]:
# hstack --> horizontally
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

hstacked=np.hstack((a,b))
print(hstacked)

[1 2 3 4 5 6]


In [ ]:
#stack --> will make 3D (by custimming axis)

a=np.array([1,2,3])
b=np.array([4,5,6])

stacked=np.stack((a,b),axis=0)
print(stacked)

print('...........................................')
stacked2=np.stack((a,b),axis=1)
print(stacked2)

[[1 2 3]
 [4 5 6]]
...........................................
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# splitting(vag kora)
a=np.array([1,2,3,4,5,6])
print(np.split(a,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# 2D array split

a=np.array([[1,2,3,4],[5,6,7,8]])
print("Original array:")
print(a)
print('.............')
print("Horizontal split into 2:")
print(np.hsplit(a,2)) # Split into 2 columns
print('.............')
print("Vertical split into 2:")
print(np.vsplit(a,2)) # Split into 2 rows

Original array:
[[1 2 3 4]
 [5 6 7 8]]
.............
Horizontal split into 2:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
.............
Vertical split into 2:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [ ]:
a=np.array([[1,2,3],[5,6,7]])
a

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
m= np.array([1,5,8,np.nan,9])
m

array([ 1.,  5.,  8., nan,  9.])

In [ ]:
np.isnan(m)

array([False, False, False,  True, False])

In [ ]:
# clean nan
cleaned = m[~np.isnan(m)] # without NaN
display(cleaned)

array([1., 5., 8., 9.])

In [ ]:
# boolean masking & filtering

arr=np.array([10,20,30,5,50])
mask= arr >= 20
print(mask)

filtered_arr=arr[mask]
print(filtered_arr)


[False  True  True False  True]
[20 30 50]


In [ ]:
# 2d arrary filtering

a=np.array([[1,2,3],[4,5,6]])
print(a)
mask2d= a > 2
print(mask2d)
filtered_arr=a[mask2d]
print(filtered_arr)

[[1 2 3]
 [4 5 6]]
[[False False  True]
 [ True  True  True]]
[3 4 5 6]


In [ ]:
n = np.array([1,2,3,4 ])

In [ ]:
type(n)

numpy.ndarray

In [ ]:
convert_in_float = n.astype(float)

In [ ]:
convert_in_float.dtype

dtype('float64')

In [ ]:
# Type Conversion
